// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz33WJwzgW7nVZpUtc2gxlItON-DJvvmE',
    appId: '1:433490481470:web:0d02173f34bf1c55a9dc6f',
    messagingSenderId: '433490481470',
    projectId: 'fooddelivdb',
    authDomain: 'fooddelivdb.firebaseapp.com',
    databaseURL: 'https://fooddelivdb-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivdb.appspot.com',
    measurementId: 'G-PFSEWXL1ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnilB2uJNop6QxAreMD9AZ7kAbq2iTyoM',
    appId: '1:433490481470:android:53cea1d0bb251524a9dc6f',
    messagingSenderId: '433490481470',
    projectId: 'fooddelivdb',
    storageBucket: 'fooddelivdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFlC5PGsJSZtB9gPsfb0cACJW88k225c',
    appId: '1:433490481470:ios:30141ac1747c1feda9dc6f',
    messagingSenderId: '433490481470',
    projectId: 'fooddelivdb',
    databaseURL: 'https://fooddelivdb-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivdb.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFlC5PGsJSZtB9gPsfb0cACJW88k225c',
    appId: '1:433490481470:ios:30141ac1747c1feda9dc6f',
    messagingSenderId: '433490481470',
    projectId: 'fooddelivdb',
    databaseURL: 'https://fooddelivdb-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivdb.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz33WJwzgW7nVZpUtc2gxlItON-DJvvmE',
    appId: '1:433490481470:web:b9e996de1245b993a9dc6f',
    messagingSenderId: '433490481470',
    projectId: 'fooddelivdb',
    authDomain: 'fooddelivdb.firebaseapp.com',
    databaseURL: 'https://fooddelivdb-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivdb.appspot.com',
    measurementId: 'G-XRK48HLH6F',
  );
}
